version: '2'
services:
  db:
    # image: datajoint/mysql:5.6
    image: datajoint/mysql:5.7
    # image: datajoint/mysql:8.0
    volumes:
      - ./my.cnf:/etc/my.cnf
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=simple
    volumes:
      - ./data2:/var/lib/mysql
    command: --character-set-server=utf8
